[package]
name = "waifu_image_tagger"
version = "0.2.0"
authors = ["hako"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rexiv2 = "0.8"
rustnao = "0.3.0-alpha.1"
serde = "*"
serde_json = "*"
crossbeam-channel = "*"
notify = "^5.0.0-pre"
reqwest = "*"
clap = "*"