[package]
name = "waifu_image_tagger"
version = "0.1.0"
authors = ["hako"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rexiv2 = "0.8"
rustnao = "0.3.0-alpha.1"
serde = "1.0.102"
serde_json = "1.0"
crossbeam-channel = "0.3.8"
notify = "=5.0.0-pre.1"
reqwest = "0.9"
clap = "2.33.0"