name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: sudo apt-get install libgexiv2-dev -y && cargo +stable build --verbose
    - name: Run tests
      run: cargo test --verbose
